// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { createTimedFetch, assertRequiredEnv } from "@/lib/server-observability";

const SUPABASE_AUTH_REQUEST_TIMEOUT_MS = 10_000;

const supabaseAuthEnv = assertRequiredEnv(
  "SupabaseAuth",
  {
    SUPABASE_URL: process.env.SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY,
  },
  ["SUPABASE_URL", "SUPABASE_PUBLISHABLE_KEY"],
);

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    console.info("[SupabaseAuth] request start");
    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    console.info("[SupabaseAuth] creating client", {
      hasUrl: Boolean(supabaseAuthEnv.SUPABASE_URL),
      hasPublishableKey: Boolean(supabaseAuthEnv.SUPABASE_PUBLISHABLE_KEY),
      requestTimeoutMs: SUPABASE_AUTH_REQUEST_TIMEOUT_MS,
    });

    const supabase = createClient<Database>(
      supabaseAuthEnv.SUPABASE_URL,
      supabaseAuthEnv.SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: createTimedFetch("SupabaseAuth", SUPABASE_AUTH_REQUEST_TIMEOUT_MS),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      },
    );

    console.info("[SupabaseAuth] fetching claims");
    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    console.info("[SupabaseAuth] claims verified", { userId: data.claims.sub });
    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
