// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { assertRequiredEnv, createTimedFetch } from "@/lib/server-observability";

const SUPABASE_REQUEST_TIMEOUT_MS = 10_000;

const supabaseServerEnv = assertRequiredEnv(
  "SupabaseAdmin",
  {
    SUPABASE_URL: process.env.SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  },
  ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"],
);

function createSupabaseAdminClient() {
  console.info("[SupabaseAdmin] creating client", {
    hasUrl: Boolean(supabaseServerEnv.SUPABASE_URL),
    hasServiceRoleKey: Boolean(supabaseServerEnv.SUPABASE_SERVICE_ROLE_KEY),
    requestTimeoutMs: SUPABASE_REQUEST_TIMEOUT_MS,
  });

  const client = createClient<Database>(
    supabaseServerEnv.SUPABASE_URL,
    supabaseServerEnv.SUPABASE_SERVICE_ROLE_KEY,
    {
      global: {
        fetch: createTimedFetch("SupabaseAdmin", SUPABASE_REQUEST_TIMEOUT_MS),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    },
  );

  console.info("[SupabaseAdmin] client ready");
  return client;
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
